/**
 * Extracts icon SVG data from Font Awesome and Game Icons into registries.
 * FA icons are bundled inline. Game Icons are written to a separate JSON file
 * loaded on demand to keep the main bundle small.
 *
 * Run: node scripts/build-icons.mjs
 * Output: src/generated/fa-icons.ts, src/generated/gi-icons.json
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const outDir = path.join(__dirname, "../src/generated");
const outFile = path.join(outDir, "fa-icons.ts");
// GI JSON goes to plugin root (alongside main.js) for runtime loading
const giJsonFile = path.join(__dirname, "../gi-icons.json");

if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

// ── Font Awesome (solid), bundled inline ──
const faSvgDir = path.join(__dirname, "../fonts/font-awesome/svgs/solid");
const faMetadataPath = path.join(__dirname, "../fonts/font-awesome/metadata/icons.json");
const faMetadata = JSON.parse(fs.readFileSync(faMetadataPath, "utf8"));

const faIcons = {};
let faCount = 0;
for (const file of fs.readdirSync(faSvgDir).filter((f) => f.endsWith(".svg"))) {
  const name = file.replace(".svg", "");
  const svg = fs.readFileSync(path.join(faSvgDir, file), "utf8");

  const viewBoxMatch = svg.match(/viewBox="([^"]+)"/);
  const pathMatch = svg.match(/<path[^>]*\sd="([^"]+)"/);
  if (!viewBoxMatch || !pathMatch) continue;

  faIcons[name] = {
    viewBox: viewBoxMatch[1],
    path: pathMatch[1],
    terms: faMetadata[name]?.search?.terms || [],
    set: "fa",
  };
  faCount++;
}

// ── Game Icons, separate JSON file ──
const giSvgDir = path.join(__dirname, "../fonts/game-icons/svgs");
const giIcons = {};
let giCount = 0;

if (fs.existsSync(giSvgDir)) {
  for (const file of fs.readdirSync(giSvgDir).filter((f) => f.endsWith(".svg"))) {
    const baseName = file.replace(".svg", "");
    const prefixedName = `gi-${baseName}`;

    const svg = fs.readFileSync(path.join(giSvgDir, file), "utf8");

    const viewBoxMatch = svg.match(/viewBox="([^"]+)"/);
    if (!viewBoxMatch) continue;

    // Game icons have two paths: background rect + icon. Get the icon path.
    const allPaths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"[^>]*/g)];
    let iconPath = null;
    for (const m of allPaths) {
      if (m[0].includes('fill="#fff"') || m[0].includes("fill='#fff'")) {
        iconPath = m[1];
        break;
      }
    }
    if (!iconPath && allPaths.length >= 2) {
      iconPath = allPaths[1][1];
    }
    if (!iconPath) continue;

    const terms = baseName.split("-").filter((t) => t.length > 1);

    giIcons[prefixedName] = {
      viewBox: viewBoxMatch[1],
      path: iconPath,
      terms,
      set: "gi",
    };
    giCount++;
  }
}

// Write Game Icons JSON (loaded at runtime by the plugin)
fs.writeFileSync(giJsonFile, JSON.stringify(giIcons), "utf8");

// Generate TypeScript file with FA icons inline + GI icon names for search
const giNames = Object.keys(giIcons).sort();

const ts = `// Auto-generated by scripts/build-icons.mjs. Do not edit.
export interface IconEntry {
  viewBox: string;
  path: string;
  terms: string[];
  set: "fa" | "gi";
}

export const FA_ICONS: Record<string, IconEntry> = ${JSON.stringify(faIcons)};

/** Game Icon names (data loaded separately from gi-icons.json) */
export const GI_ICON_NAMES: string[] = ${JSON.stringify(giNames)};

/** Game Icon search terms indexed by name */
export const GI_ICON_TERMS: Record<string, string[]> = ${JSON.stringify(
  Object.fromEntries(giNames.map((n) => [n, giIcons[n].terms]))
)};

export const ALL_ICON_NAMES: string[] = ${JSON.stringify(
  [...Object.keys(faIcons), ...giNames].sort()
)};
`;

fs.writeFileSync(outFile, ts, "utf8");
console.log(`Generated ${faCount} FA (bundled) + ${giCount} Game Icons (JSON) = ${faCount + giCount} total`);
