/**
 * Extracts Font Awesome solid SVG icon data into a JSON registry.
 * Run: node scripts/build-icons.mjs
 * Output: src/generated/fa-icons.ts
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const svgDir = path.join(__dirname, "../fonts/font-awesome/svgs/solid");
const outFile = path.join(__dirname, "../src/generated/fa-icons.ts");

// Read icons.json for search terms
const metadataPath = path.join(__dirname, "../fonts/font-awesome/metadata/icons.json");
const metadata = JSON.parse(fs.readFileSync(metadataPath, "utf8"));

const icons = {};
const files = fs.readdirSync(svgDir).filter((f) => f.endsWith(".svg"));

for (const file of files) {
  const name = file.replace(".svg", "");
  const svg = fs.readFileSync(path.join(svgDir, file), "utf8");

  // Extract viewBox and path d attribute
  const viewBoxMatch = svg.match(/viewBox="([^"]+)"/);
  const pathMatch = svg.match(/<path[^>]*\sd="([^"]+)"/);

  if (!viewBoxMatch || !pathMatch) continue;

  const searchTerms = metadata[name]?.search?.terms || [];

  icons[name] = {
    viewBox: viewBoxMatch[1],
    path: pathMatch[1],
    terms: searchTerms,
  };
}

// Generate TypeScript file
const outDir = path.dirname(outFile);
if (!fs.existsSync(outDir)) fs.mkdirSync(outDir, { recursive: true });

const ts = `// Auto-generated by scripts/build-icons.mjs — do not edit
export interface FAIcon {
  viewBox: string;
  path: string;
  terms: string[];
}

export const FA_ICONS: Record<string, FAIcon> = ${JSON.stringify(icons)};

export const FA_ICON_NAMES: string[] = ${JSON.stringify(Object.keys(icons).sort())};
`;

fs.writeFileSync(outFile, ts, "utf8");
console.log(`Generated ${Object.keys(icons).length} icons → ${outFile}`);
